import Head from "next/head";

export default function Eoc() {
  return (
    <>
      <Head>
        <title>ePauta - Ingeniería Civil en Obras Civiles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      </main>
    </>
  );
}
