import Head from "next/head";
import Breadcrumb from "../Breadcrumb";
import Footer from "../Footer";
import RamoBox from "../RamoBox";

export default function Carrera(props: any) {
  return (
    <>
      <Head>
        <title>ePauta - {props.nombreCarrera}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-red-500 md:h-screen h-full">
        <div className="container mx-auto">
          <Breadcrumb carrera={props.nombreCarrera} enlaceCarrera={props.enlaceCarrera}/>
          <div className="grid md:grid-cols-3 lg:grid-cols-5 gap-6 p-4">
            {Object.keys(props.Malla).map((key: any) => {
              return (
                <a
                  href={props.enlaceCarrera + "/" + props.Malla[key].enlace}
                >
                  <div className="bg-white px-4 py-8 rounded hover:text-red-500">{props.Malla[key].nombre}</div>
                </a>
              );
            })}
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
