import Head from "next/head";
import Breadcrumb from "../../components/Breadcrumb";
import FileBox from "../../components/FileBox";

import axios from "axios";

//files
import React from "react";
import Footer from "../Footer";

const controlesURL =
  "https://mvmeo.github.io/apipautas/carreras/plan-comun/programacion/controles.json";
const solemnesURL =
  "https://mvmeo.github.io/apipautas/carreras/plan-comun/programacion/solemnes.json";
const examenesURL =
  "https://mvmeo.github.io/apipautas/carreras/plan-comun/programacion/examenes.json";


export default function Ramo(props:any) {
  return (
    <>
      <Head>
        <title>ePauta - {props.nombreCarrera} / {props.nombreRamo}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="container mx-auto">
          <Breadcrumb carrera={props.nombreCarrera} enlaceCarrera={props.enlaceCarrera} ramo={props.nombreRamo} />

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mx-4 mt-4">
            <FileBox Files={props.Controles} carrera={props.enlaceCarrera} ramo={props.enlaceRamo} evaluacion="controles" />
            <FileBox Files={props.Solemnes} carrera={props.enlaceCarrera} ramo={props.enlaceRamo} evaluacion="solemnes" />
            <FileBox Files={props.Examenes} carrera={props.enlaceCarrera} ramo={props.enlaceRamo} evaluacion="examenes" />
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
